# Generated by Django 5.1.5 on 2025-02-28 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('estatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('localidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('localidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Boletos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField()),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.eventos')),
                ('tipo_boleto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.tipo_boleto')),
            ],
        ),
    ]
