# Generated by Django 5.1.5 on 2025-03-04 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
